InventoryProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from accounts.views import LoginView


urlpatterns = [
    path('dj-admin/', admin.site.urls),

    path('test', views.Test),

    path('', LoginView, name = 'login'),
    
    # including Apps urls
    path('accounts/', include('accounts.urls')),
    path('components/', include('components.urls')),
    path('bag/', include('bag.urls')),
    path('order/', include('order.urls')),
    path('leave/', include('leave.urls')),
    path('dashboard/', include('dashboard.urls')),

]

bag/urls.py
from django.urls import path
from . import views

app_name = 'bag'

urlpatterns = [
    path('add-to-bag/<str:component_id>', views.add_to_bag, name = 'add_to_bag'),
    path('bag-details/', views.bag_details, name = 'bag_details'),
    path('remove-item/<str:component_id>', views.remove_item, name = 'remove-item'),
    path('delete-item/<str:component_id>', views.delete_bag_items, name = 'delete-items'),
    path('request-components', views.request_components, name = 'request_components')
]

components/urls.py
from django.urls import path
from . import views

app_name = 'components'

urlpatterns = [
    path('',views.ComponentListView, name = 'component-list-all'),  
    path('<str:id>/', views.CatComponentListView, name =  'component-list-cat'),
    
    path('category/all', views.all_categories, name = 'all-categories'),
    path('add/category', views.add_category, name = 'add-category'),
    path('update/category/<str:id>', views.update_category, name = 'update-category'),
    path('delete/category/<str:id>', views.delete_category, name='delete-category'),
    path('detail/component/<str:id>', views.detailed_component, name = 'component-detail'),


    path('admin/all', views.allcomponents, name = 'all-components-admin'),
    path('admin/add-component', views.add_component, name = 'add-component'),
    path('admin/update-component/<str:id>', views.update_component, name = 'update-component'),
    path('admin/delete-component/<str:id>', views.delete_component, name = 'delete-component'),

]

components/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


##################   COMPONENT CATEGOTY    #####################
class ComponentCategory(models.Model):
    name = models.CharField(max_length=75, unique = True)
    # slug = models.SlugField(max_length=100, unique = True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to = 'component_category', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Component Category'
        verbose_name_plural = 'Component Categories'
    
    def __str__(self):
        return '{}'.format(self.name)
    
    def get_url(self):
        return reverse('components:component-list-cat', args=[self.id])
            
    
 
################           COMPONENT       ######################
class Component(models.Model):
    
    def auto_comp_id(): 
        no = Component.objects.count()
        str1 = 'VSTNHC'
        list2 = ['0','0','0','0','0']
        item = no+1   
        str_item = str(item)   
        list_item = list(str_item)   
        leng = len(list_item)
        con = 5-leng   
        list2[con:] = list_item
        result = ''.join(map(str, list2))
        final = str1+result   
        return final  
        
    component_id = models.CharField(max_length = 20, default = auto_comp_id, editable=False)
    name = models.CharField(max_length=75, unique = True)
    # slug = models.SlugField(unique=True, max_length = 100)
    category = models.ForeignKey(ComponentCategory, on_delete=models.CASCADE)
    component_location = models.CharField(max_length =  100, default='inventory')
    vendor = models.CharField(max_length=100, null = True, blank=True)
    invoice = models.CharField(max_length=25, blank=True, null=True)
    component_id_by_vendor = models.CharField(blank = True, null=True, max_length=35)
    date_of_order = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to = 'components', blank=True, null=True)
    avialable = models.BooleanField(default=True)
    stock = models.IntegerField()
    price = models.DecimalField(max_digits =10, decimal_places=2)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Component'
        verbose_name = 'Components'
    
    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        pass


    

components/forms.py
from django import forms
from .models import ComponentCategory, Component
from django.contrib.admin.widgets import AdminDateWidget

class CategoryForm(forms.ModelForm):
    class Meta:
        model = ComponentCategory
        fields = ('name', 'description')
        # widgets = {
        #     'name' : forms.TextInput(attrs={'class':'form-control'}),
        #     # 'image': forms.ImageField(attrs = {'class':'form-control'}),
        #     'description': forms.Textarea(attrs = {'class': 'form-control'}),
        # }

class ComponentForm(forms.ModelForm):
    class Meta:
        model = Component
        fields = ('name', 'category', 'component_location', 'vendor', 'invoice','component_id_by_vendor', 'date_of_order', 'stock', 'price', 'description')
        
        

components/views.py
from django.http import request
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Component, ComponentCategory
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from .forms import CategoryForm, ComponentForm
from django.contrib import messages



# Create your views here.

#################################################################
#################   FETCHING COMPONENTS    ######################
#################################################################

@login_required
def ComponentListView(request):
    qs = Component.objects.filter(avialable = True)
    cat = ComponentCategory.objects.all()
    return render(request, 'components/components.html', {'qs':qs, 'cat':cat})

@login_required
def CatComponentListView(request, id):
    qs = Component.objects.filter(category__id__exact = id, avialable = True)
    cat = ComponentCategory.objects.all()
    return render(request, 'components/components.html', {'qs':qs, 'cat':cat})



#################################################################
###################    CRUD CATEGORY     ########################
#################################################################

@staff_member_required(login_url='accounts:auth-login')
def all_categories(request):
    cats = ComponentCategory.objects.all()
    return render(request, 'components/category_list.html', {'cats':cats})


@staff_member_required(login_url='accounts:auth-login')
def add_category(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid:
            form.save()
            messages.info(request, 'New category added')
            return redirect('components:all-categories')
        else:
            messages.info(request, 'form data invalid')            
    else:
        form = CategoryForm()

    return render(request, 'components/create_category.html')


@staff_member_required(login_url='accounts:auth-login')
def update_category(request, id):
    if request.method == 'POST':
        obj = get_object_or_404(ComponentCategory, id = id)
        form = CategoryForm(request.POST, instance=obj)

        if form.is_valid():
            form.save()
            messages.info(request,'category updated successfully')

            return redirect('components:all-categories')

        else:
            messages.info(request, 'form data is invalid')
    else:
        obj = get_object_or_404(ComponentCategory, id = id)
        form = CategoryForm(instance = obj)

        return render(request, 'components/update_category.html', {'form':form})

        
    


@staff_member_required(login_url='accounts:auth-login')
def delete_category(request, id):
    obj = get_object_or_404(ComponentCategory, id = id)
    obj.delete()
    messages.info(request, 'category deleted successfully')
    return redirect('components:all-categories')


#################################################################
##################       CRUD COMPONENTS        #################
#################################################################

@staff_member_required(login_url='accounts:auth-login')
def allcomponents(request):
    all_com = Component.objects.all()
    return render(request, 'components/all-components-admin.html', {'all_com':all_com})

@staff_member_required(login_url='accounts:auth-login')
def add_component(request):
    if request.method == "POST":
        form = ComponentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'new component added successfully')
            return redirect('components:all-components-admin')
        else:
            messages.info(request, 'form data is invalid')
    else:
        form = ComponentForm()

    return render(request, 'components/create_component.html', {'form':form})


@staff_member_required(login_url='accounts:auth-login')
def update_component(request, id):
    if request.method == 'POST':
        obj = get_object_or_404(Component, id = id)
        form = ComponentForm(request.POST, instance=obj)

        if form.is_valid():
            form.save()
            messages.info(request,'component updated successfully')

            return redirect('components:all-components-admin')

        else:
            messages.info(request, 'form data is invalid')
    else:
        obj = get_object_or_404(Component, id = id)
        form = ComponentForm(instance = obj)

    return render(request, 'components/update_component.html', {'form':form})



@staff_member_required(login_url='accounts:auth-login')
def delete_component(request, id):
    pass


@login_required(login_url='accounts:auth-login')
def detailed_component(request, id):
    component = Component.objects.get(id = id)    
    return render(request, 'components/component_detail.html', {'component':component})

components/templates/components/all-components-admin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
        Components | Vistan Nextgen Pvt Ltd
{% endblock%}
            


{% block content %}
      
      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <ul class="breadcrumb breadcrumb-style ">
            
            <li class="breadcrumb-item">
              <a href="index-2.html">
                <i data-feather="home"></i></a>
            </li>
            <!-- <li class="breadcrumb-item active">Dashboard</li>    -->
            <li class="breadcrumb-item active">All Components</li>                   
          </ul> 

          {% if messages %}
            {% for i in messages %}
              <div class="alert alert-success alert-dismissible show fade">
                      <div class="alert-body">
                        <button class="close" data-dismiss="alert">
                          <span>&times;</span>
                        </button>
                        {{i}}
                      </div>
                    </div>
            {% endfor %}
          {% endif %}

          
          {% include 'components/all_comp_table.html' %}              
          
        </section>
      </div>
    </div>
{% endblock %}



{% block js %}
<script>
  function myFunction() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("myTable");

    console.log(input, filter, table);
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[1];
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }



  function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("myTable");
  switching = true;  
  dir = "asc"; 
  while (switching) {    
    switching = false;
    rows = table.rows;   
    for (i = 1; i < (rows.length - 1); i++) {
      shouldSwitch = false;
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {          
          shouldSwitch = true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {          
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {     
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;      
      switchcount ++;
    } else {
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}
  


{% if messages %}
console.log('message')

        iziToast.show({
                        title: 'Hii',
                        message: '{% for i in messages %}{{i}}{%endfor%}',
                        position: 'topRight',
                        color: 'success'
                    });
 
  {% else %}
  console.log('no messages')
  {% endif %}

</script>
{% endblock %}

components/templates/components/all_comp_table.html
<div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Components List</h4>
                    <div class="card-header-form">
                      
                      <form>
                        
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search by name" id = "myInput" onkeyup="myFunction()">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                          
                          
                          <a href="{% url 'components:add-component' %}"><div class="badge badge-secondary">Add Component</div></a>
                          

                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="table-responsive">
                  <div class="card-body p-0">
                      <table class="table table-striped" id = "myTable">
                        <tr>
                          <th class="text-center" onclick="sortTable(0)">Component ID&nbsp;<i class="fas fa-sort"></i></th>
                          <th onclick="sortTable(1)">Component Name&nbsp;<i class="fas fa-sort"></i></th>
                          <th>Category</th>
                          <th>Stock</th>
                          <th>Availability</th>
                          {% comment %} <th>Status</th>{% endcomment %}
                          
                          <th>Action</th>
                        </tr>
                        {% for i in all_com %}
                        <tr>
                          

                              <td class="p-0 text-center">
                                  {{i.component_id}}
                                </div>
                              </td>
                              <td>{{i.name}}</td>
                              <td>{{i.category|lower}}</td>
                              <td>{{i.stock}}</td>

                              {% comment %} <td>
                                {% if i.avialable == True %}
                                <div class="badge badge-success">Avaialable</div>
                                {% else %}
                                <div class="badge badge-danger">Unavaialable</div>                              
                                {% endif%}
                              </td> {% endcomment %}
                                         
                         
                          
                          <td>
                            {% if i.stock <= 0 %}
                              <div class="badge badge-warning">No stock Avaialable</div>                           
                            {% else %}
                              <div class="badge badge-success">stock Avaialable</div>          
                    
                            {% endif %}
                          </td>

                              <td>
                                <a class="btn btn-md btn-dark" style="text-decoration: none;" href="{% url 'components:component-detail' i.id %}"
                                  data-toggle="tooltip" data-placement="top"
                                  title="view."
                                ><i class="fas fa-eye"></i> </a>&nbsp;


                                <a class="btn btn-md btn-info" style="text-decoration: none;" 
                                   href="{% url 'components:update-component' i.id %}"
                                  data-toggle="tooltip" data-placement="top"
                                  title="edit"
                                ><i class="fas fa-pen"></i> </a>&nbsp;

                                {% comment %} <a class="btn btn-md btn-danger" style="text-decoration: none;" 
                                   href=""
                                  data-toggle="tooltip" data-placement="top"
                                  title="delete"
                                ><i class="fas fa-trash"></i> </a>&nbsp; {% endcomment %}

                                                            
                              </td>

                          
                        </tr>  
                        {% endfor %}   
                       
                     
                      </table>
                    </div>
                  </div>
                </div>
              </div>
</div>

{% block js %}

{% if messages%}
  <script>
        iziToast.show({
                        title: 'yay!!',
                        message: '{% for i in messages %}{{i}}{%endfor%}',
                        position: 'topRight',
                        color: 'green'
                        /* {% for i in messages%}
                          {% ifequal 'danger' i.tags %} red
                          {% else %} green
                          {% endifequal%}
                        {% endfor %} */
                    });
  </script>
  {% endif %}

{% endblock %}

components/templates/components/category_table.html
<div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Categories List</h4>
                    <div class="card-header-form">
                      
                      <form>
                        
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search by name" id = "myInput" onkeyup="myFunction()">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                          <a href="{% url 'components:add-category' %}"><div class="badge badge-secondary">Add category</div></a>

                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="table-responsive">
                  <div class="card-body p-0">
                      <table class="table table-striped" id = "myTable">
                        <tr>
                          <th class="text-center" onclick="sortTable(0)">Category ID&nbsp;<i class="fas fa-sort"></i></th>
                          <th onclick="sortTable(1)">Category Name&nbsp;<i class="fas fa-sort"></i></th>
                          <th>Description</th>
                          <th>Action</th>                 
                        </tr>
                        {% for i in cats %}
                        <tr>
                          

                              <td class="p-0 text-center">
                                  {{i.id}}
                                </div>
                              </td>
                              <td>{{i.name}}</td>
                              <td>

                              {{i.description|slice:":40"}}...
                              </td>

                              <td>
                                <a href="{% url 'components:update-category' i.id %}" class="btn btn-info btn-md"
                                    data-toggle="tooltip" data-placement="top"
                                    title="edit"
                                ><i class="fas fa-pen"></i></a>
                                &nbsp;
                                {% comment %} <a href="{% url 'components:delete-category' i.id %}" class="btn btn-danger btn-md"
                                  data-toggle="tooltip" data-placement="top"
                                  title="Delete"
                                
                                ><i class="fas fa-trash"></i></a> {% endcomment %}

                              </td>
               </tr>  
                        {% endfor %}   
                       
                     
                      </table>
                    </div>
                  </div>
                </div>
              </div>
</div>

components/templates/components/component_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
        Component Detail | Vistan Nextgen Pvt Ltd
{% endblock%}
            


{% block content %}
      
      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <ul class="breadcrumb breadcrumb-style ">
            
            <li class="breadcrumb-item">
              <a href="index-2.html">
                <i data-feather="home"></i></a>
            </li>
            <!-- <li class="breadcrumb-item active">Dashboard</li>    -->
            <li class="breadcrumb-item active">Component Details</li>                   
          </ul>   

          {% if messages %}
            {% for i in messages %}
              <div class="alert alert-success alert-dismissible show fade">
                      <div class="alert-body">
                        <button class="close" data-dismiss="alert">
                          <span>&times;</span>
                        </button>
                        {{i}}
                      </div>
                    </div>
            {% endfor %}
          {% endif %}   


          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Component Details</h4>

                    {% if user.is_staff %}{% else %}<div class="card-header-form">
                      
                      <form>
                        
                        <div class="input-group">
                          
                          <div class="input-group-btn">
                            <a href="{% url 'bag:add_to_bag' component.component_id %}">
                              <div class="badge badge-primary">Add to bag</div>
                            </a>
                          </div>
                         </div>
                      </form>
                    </div>{% endif %}
                  </div>
                  <div class="card-body">
                      <div class="row">
                          <div class="col-1"></div>
                          <div class="col-10">
                              <div class="container">
                                Component ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ::  &nbsp;&nbsp;<span class="col-blue">{{component.component_id}}</span> <br><br>  
                                Component ID(by Vendor) &nbsp;&nbsp;&nbsp;&nbsp;:: &nbsp;&nbsp;<span class="col-blue">{{component.component_id_by_vendor}}</span> <br><br>
                                Component Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::  &nbsp;&nbsp;<span class="col-blue">{{component.name}}</span> <br><br>
                                Component Category &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:: &nbsp;&nbsp;<span class="col-blue">{{component.category}}</span><br><br>
                                Component Location &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:: &nbsp;&nbsp;<span class="col-blue">{{component.component_location}}</span><br><br>
                                {%if user.is_staff%} Date of Order &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:: &nbsp;&nbsp;<span class="col-blue">{{component.date_of_order|date:"d-m-Y"}}</span><br><br>
                                Component Added &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:: &nbsp;&nbsp;<span class="col-blue">{{component.created_at|date:"d-m-Y"}}</span> <br><br>
                                Component Updated &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:: &nbsp;&nbsp;<span class="col-blue">{{component.updated_at|date:"d-m-Y"}}</span> <br><br>
                                avialable &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  :: &nbsp;&nbsp;<span class="col-blue">{{component.avialable}}</span><br><br>
                                stock &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:: &nbsp;&nbsp;<span class="col-blue">{{component.stock}}</span>  <br><br>    
                                price  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:: &nbsp;&nbsp;<span class="col-blue">{{component.price}}</span> <br><br>{% endif %}
                                description &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;::  &nbsp;&nbsp;<span class="col-blue">{{component.description}}</span><br><br>

                              </div>
                             
                          </div>

                         <div class="col-1"></div>

                          
                      </div>
                    
                  </div>
                </div>
              </div>
            </div>
          </div>    

          

          
          
        </section>
      </div>
    </div>
{% endblock %}












      

components/templates/components/table.html
<div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Components List</h4>
                    <div class="card-header-form">
                      
                      <form>
                        
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search by name" id = "myInput" onkeyup="myFunction()">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="table-responsive">
                  <div class="card-body p-0">
                      <table class="table table-striped" id = "myTable">
                        <tr>
                          <th class="text-center" onclick="sortTable(0)">Component ID&nbsp;<i class="fas fa-sort"></i></th>
                          <th onclick="sortTable(1)">Component Name&nbsp;<i class="fas fa-sort"></i></th>
                          <th>Category</th>
                          <th>Details</th>
                          {% comment %} <th>Status</th>{% endcomment %}
                          
                          <th>Action</th>
                        </tr>
                        {% for i in qs %}
                        <tr>
                          

                              <td class="p-0 text-center">
                                  {{i.component_id}}
                                </div>
                              </td>
                              <td>{{i.name}}</td>
                              <td>{{i.category|lower}}</td>
                              <td><a style="text-decoration: none;" href="{% url 'components:component-detail' i.id %}"><i class="fas fa-eye"></i> View</a></td>

                              {% comment %} <td>
                                {% if i.avialable == True %}
                                <div class="badge badge-success">Avaialable</div>
                                {% else %}
                                <div class="badge badge-danger">Unavaialable</div>                              
                                {% endif%}
                              </td> {% endcomment %}
                                         
                         
                          
                          <td>
                            {% if i.stock <= 0 %}
                              <div class="badge badge-warning">No stock Avaialable</div>                           
                            {% else %}
                              <a href="{% url 'bag:add_to_bag' i.component_id %}" class="btn btn-sm btn-primary">Add to bag</a>
                            {% endif %}
                          </td>
                          
                        </tr>  
                        {% endfor %}   
                       
                     
                      </table>
                    </div>
                  </div>
                </div>
              </div>
</div>