InventoryProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from accounts.views import LoginView


urlpatterns = [
    path('dj-admin/', admin.site.urls),

    path('test', views.Test),

    path('', LoginView, name = 'login'),
    
    # including Apps urls
    path('accounts/', include('accounts.urls')),
    path('components/', include('components.urls')),
    path('bag/', include('bag.urls')),
    path('order/', include('order.urls')),
    path('leave/', include('leave.urls')),
    path('dashboard/', include('dashboard.urls')),

]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('auth-login/', views.LoginView, name = 'auth-login'),
    path('auth-register/', views.RegisterEmployee, name = 'auth-register'),
    path('auth-logout/', views.LogoutView, name = 'auth-logout'),
    path('auth-change-password/', views.ChangePasswordView, name = 'auth-change-password'),

    path('all-employees', views.allEmployees, name = 'all-employes'),
    path('edit-employee/<str:id>', views.editEmployee, name = 'edit-employee'),
    path('edit-profile/<str:id>', views.editUserProfile, name = 'edit-user-profile'),
    path('delete-employee/<str:id>', views.deleteEmployee, name = 'delete-employee'),
    path('change-password/<str:id>', views.ChangePasswordView, name = 'change-password'),

    path('add-department/', views.create_dept, name = 'create-dept'),
    path('update-dept/<str:id>', views.update_dept, name = 'update-dept'),
    path('delete-dept/<str:id>', views.delete_dept, name = 'delete-dept'),
    path('all-depts', views.dept_list, name = 'all-depts'),

]

bag/urls.py
from django.urls import path
from . import views

app_name = 'bag'

urlpatterns = [
    path('add-to-bag/<str:component_id>', views.add_to_bag, name = 'add_to_bag'),
    path('bag-details/', views.bag_details, name = 'bag_details'),
    path('remove-item/<str:component_id>', views.remove_item, name = 'remove-item'),
    path('delete-item/<str:component_id>', views.delete_bag_items, name = 'delete-items'),
    path('request-components', views.request_components, name = 'request_components')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.



class Department(models.Model):
    dept_name = models.CharField(max_length = 25)
    created_at = models.DateTimeField(auto_now_add=True)
    dept_description = models.TextField()
    dept_pic = models.ImageField(upload_to = 'Dept_profile_images', null = True, blank = True)
    
    class Meta:
        verbose_name = 'Department'
        verbose_name_plural = 'Departments'
        ordering = ('-id',)
    
    def __str__(self):
        return '{}'.format(self.dept_name)




gender_choices = (
    ('male', 'male'),
    ('female', 'female')
)
class CustomUser(AbstractUser):
    id = models.BigAutoField(primary_key = True)
    employee_id = models.CharField(max_length = 10, null=True, blank=True)
    department = models.ForeignKey(Department, on_delete = models.CASCADE, null=True)
    mobile = models.CharField(max_length = 10, null=True, blank=True)
    gender = models.CharField(choices=gender_choices, max_length=10, default = 'male', null=True, blank=True)
    profile_pic = models.ImageField(upload_to = 'profil_images', null = True, blank = True, )
    date_of_joining = models.DateField(auto_now = True, null=True, blank=True)
    designation = models.CharField(max_length=25, null=True, blank=True)
    status = models.BooleanField(default = True)
    employee_leaves = models.IntegerField(blank=True, null=True, default = 20)

    class Meta:
        verbose_name = 'User'
        verbose_name = 'User'
        ordering = ('-id', )
    
    def __str__(self):
        return '{}'.format(self.first_name+" "+self.last_name)

accounts/forms.py
from .models import CustomUser as User
from django import forms
from .models import Department

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'mobile', 'department', 'designation', 'employee_id', 'employee_leaves')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'mobile')

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ('dept_name', 'dept_description')

accounts/views.py
from django.contrib import auth
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from .models import CustomUser as User, Department
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
from .forms import UserForm, UserProfileForm, DepartmentForm


def is_employee(user):
    return user.groups.filter(name='employee').exists()



#################     LOGIN     ######################
def LoginView(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username = username, password = password)

        if user is not None:
            if user.is_active:
                request.session.set_expiry(86400)
                login(request,user)
                # messages.success(request, 'You have logged in successfully')
                if user.is_superuser:
                    return redirect('dashboard:admin-dashboard')


                else:
                    return redirect('components:component-list-all')
                # redirect to dashboard
        else:
            messages.warning(request, 'Invalid credentials')    
    return render(request, 'accounts/auth-login.html')


################   LOGOUT     ##############################
@login_required
def LogoutView(request):
    logout(request)
    messages.info(request, 'Logged out successfully!')
    return redirect('accounts:auth-login')
    

###############   Register employee    ###############
@user_passes_test(lambda u:u.is_superuser)
def RegisterEmployee(request):
    if request.method == "POST": 
        # fetching form data       
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        employee_id = request.POST['employee_id']        
        
        
        if User.objects.filter(username = username).exists():          # checking for username
            messages.warning(request, 'username already taken')
        
        elif User.objects.filter(email = email).exists():              # checking for email
            messages.warning(request, 'Email already exists')
        
        elif User.objects.filter(employee_id = employee_id).exists():   # checking for employee_id
            messages.warning(request, 'Employee ID already exists')

        else:
            if password1 == password2:     # checking for password match
                user = User(username = username,
                            first_name = first_name,
                            last_name = last_name,
                            email = email,
                            password = password1,
                            employee_id = employee_id,
                            )
                user.set_password(password1)
                user.save()
                Employee_group = Group.objects.get(name = 'employee')      # Fetching employee group
                Employee_group.user_set.add(user)                          # Adding user to employee group

                messages.success(request, 'New user has added successfully')     
                # return HttpResponse('employee created')
                return redirect('accounts:all-employes')
            
            else:
                messages.warning(request, 'passwords do not matched')

    return render(request, 'accounts/auth-register.html')


###########    ALL EMPLOYEES     ######################
@staff_member_required(login_url='accounts:auth-login')
def allEmployees(request):
    emp = User.objects.all()
     
    # return HttpResponse('Hii')
    return render(request, 'accounts/all_employees.html', {'emp':emp})


###############    EDIT EMPLOYEES     ######################
@staff_member_required(login_url='accounts:auth-login')
def editEmployee(request, id):
    if request.method == "POST":
        obj = get_object_or_404(User, id = id)
        form = UserForm(request.POST, instance=obj)

        if form.is_valid():
            form.save()
            messages.info(request, 'employee profile updated')
            return redirect('accounts:all-employes')
        else:
            messages.info(request, 'invalid form data')
    else:
        obj = get_object_or_404(User, id = id)
        form = UserForm(instance =obj)
    return render(request, 'accounts/edit_employee.html', {'form':form})

###############  EDIT PROFILE(FOR EMPLOYEE SIDE)   #########
# @user_passes_test(is_employee)
def editUserProfile(request, id):
    if request.method == "POST":
        obj = get_object_or_404(User, id = id)
        form = UserProfileForm(request.POST, instance=obj)

        if form.is_valid():
            form.save()
            messages.info(request, 'Profile has been updated')
            return redirect('components:component-list-all')
            # REDIRECTION IS NOT SET AFTER UPDATING(REDIRECT TO DASHBOARD)
        else:
            messages.info(request, 'invalid form data')
    else:
        obj = get_object_or_404(User, id = id)
        form = UserProfileForm(instance =obj)
    return render(request, 'accounts/edit_user_profile.html', {'form':form})




#############    DELETE EMPLOYEES     ######################
@staff_member_required(login_url='accounts:auth-login')
def deleteEmployee(request, id):
    employee = User.objects.get(id = id)
    employee.delete()
    messages.info(request, 'User deleted successfully')
    return redirect('accounts:all-employes')


###############    CHANGE PASSWORD     ################
def ChangePasswordView(request, id):
    obj = User.objects.get(id = id)
    if request.method == "POST":
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        
        if password1 == password2:
            obj.set_password(password1)
            obj.save()
            messages.info(request, 'password changed successfully')
            return redirect('accounts:all-employes')
        else:
            messages.info(request, 'passwords not matched') 
    return render(request, 'accounts/reset_password.html')

#############    CREATE DEPARTMENT   ####################
@staff_member_required(login_url='accounts:auth-login')
def create_dept(request):
    if request.method == "POST":
        dept_name = request.POST['dept_name']
        dept_description = request.POST['dept_description']

        dept = Department.objects.create(dept_name = dept_name,dept_description = dept_description)
        dept.save()
        return redirect('accounts:all-depts')

    return render(request, 'accounts/create_dept.html')

@staff_member_required(login_url='accounts:auth-login')
def update_dept(request, id):
    if request.method == "POST":
        obj = get_object_or_404(Department, id = id)
        form = DepartmentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'Department updated succesfully')
            return redirect('accounts:all-depts')
        else:
            messages.info(request, 'Invalid form data')
    else:
        obj = get_object_or_404(Department, id = id)
        form = DepartmentForm(instance = obj)

    return render(request, 'accounts/update_dept.html', {'form':form})

@staff_member_required(login_url='accounts:auth-login')
def delete_dept(request, id):
    dept = Department.objects.get(id = id)
    dept.delete()
    messages.info(request, 'department deleted succesfully')
    return redirect('accounts:all-depts')
    

@staff_member_required(login_url='accounts:auth-login')
def dept_list(request):
    dept = Department.objects.all()
    return render(request, 'accounts/all_depts.html', {'dept':dept})
    

accounts/templates/accounts/all_depts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
        Departments | Vistan Nextgen Pvt Ltd
{% endblock%}
            
<!-- Dhanush -->

{% block content %}
      
      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <ul class="breadcrumb breadcrumb-style ">

            
            
            <li class="breadcrumb-item">
              <a href="index-2.html">
                <i data-feather="home"></i></a>
            </li>
            <li class="breadcrumb-item active">All Departments</li>  
            
          </ul> 

          {% if messages %}
            {% for i in messages %}
              <div class="alert alert-success alert-dismissible show fade">
                      <div class="alert-body">
                        <button class="close" data-dismiss="alert">
                          <span>&times;</span>
                        </button>
                        {{i}}
                      </div>
                    </div>
            {% endfor %}
          {% endif %}


          <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Department List</h4>
                    <div class="card-header-form">
                      
                      <form>
                        
                        <div class="input-group">
                          
                          <a href="{% url 'accounts:create-dept' %}"><div class="badge badge-secondary">Add Department</div></a>

                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="table-responsive">
                  <div class="card-body p-0">
                      <table class="table table-striped" id = "myTable">
                        <tr>
                          <th class="text-center" onclick="sortTable(0)">Department ID&nbsp;</th>
                          <th onclick="sortTable(1)">Department Name&nbsp;</th>
                          <th>Description</th>
                          <th>Action</th>                 
                        </tr>
                        {% for i in dept %}
                        <tr>
                          

                              <td class="p-0 text-center">
                                  {{i.id}}
                                </div>
                              </td>
                              <td>{{i.dept_name}}</td>
                              <td>

                              {{i.dept_description|slice:":40"}}...
                              </td>

                              <td>
                                <a href="{% url 'accounts:update-dept' i.id %}" class="btn btn-info btn-md"
                                    data-toggle="tooltip" data-placement="top"
                                    title="edit"
                                ><i class="fas fa-pen"></i></a>
                                &nbsp;
                                {% comment %} <a href="{% url 'accounts:delete-dept' i.id %}" class="btn btn-danger btn-md"
                                  data-toggle="tooltip" data-placement="top"
                                  title="Delete"
                                
                                ><i class="fas fa-trash"></i></a> {% endcomment %}

                              </td>
               </tr>  
                        {% endfor %}   
                       
                     
                      </table>
                    </div>
                  </div>
                </div>
              </div>
</div>


                       
          
        </section>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/all_employees.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
        Employees | Vistan Nextgen Pvt Ltd
{% endblock%}
            


{% block content %}
      
      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <ul class="breadcrumb breadcrumb-style ">
            
            <li class="breadcrumb-item">
              <a href="index-2.html">
                <i data-feather="home"></i></a>
            </li>
            <!-- <li class="breadcrumb-item active">Dashboard</li>    -->
            <li class="breadcrumb-item active">All Employees</li>                   
          </ul>

          {% if messages %}
            {% for i in messages %}
              <div class="alert alert-success alert-dismissible show fade">
                      <div class="alert-body">
                        <button class="close" data-dismiss="alert">
                          <span>&times;</span>
                        </button>
                        {{i}}
                      </div>
                    </div>
            {% endfor %}
          {% endif %} 

          {% include 'accounts/emp_table.html' %}              
          
        </section>
      </div>
    </div>
{% endblock %}



{% block js %}
<script>
  function myFunction() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("myTable");

    console.log(input, filter, table);
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[1];
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }



  function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
  table = document.getElementById("myTable");
  switching = true;  
  dir = "asc"; 
  while (switching) {    
    switching = false;
    rows = table.rows;   
    for (i = 1; i < (rows.length - 1); i++) {
      shouldSwitch = false;
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      if (dir == "asc") {
        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {          
          shouldSwitch = true;
          break;
        }
      } else if (dir == "desc") {
        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {          
          shouldSwitch = true;
          break;
        }
      }
    }
    if (shouldSwitch) {     
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
      switching = true;      
      switchcount ++;
    } else {
      if (switchcount == 0 && dir == "asc") {
        dir = "desc";
        switching = true;
      }
    }
  }
}
  


{% if messages %}
console.log('message')

        iziToast.show({
                        title: 'Hii',
                        message: '{% for i in messages %}{{i}}{%endfor%}',
                        position: 'topRight',
                        color: 'success'
                    });
 
  {% else %}
  console.log('no messages')
  {% endif %}

</script>
{% endblock %}

accounts/templates/accounts/auth-base.html
<html lang="en">
<!DOCTYPE html>
{% load static %}



<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>{% block title %}{% endblock %}</title>
  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static "assets/css/app.min.css" %}">
  <link rel="stylesheet" href="{% static "assets/bundles/bootstrap-social/bootstrap-social.css" %}">
  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
  <link rel="stylesheet" href="{% static "assets/css/components.css" %}">
  <!-- Custom style CSS -->
  <link rel="stylesheet" href="{% static "assets/css/custom.css" %}">
  <link rel='shortcut icon' type='image/x-icon' href="{% static "assets/img/favicon_vistan.ico" %}"/>
  <link rel="stylesheet" href="{% static "assets/bundles/izitoast/css/iziToast.min.css" %}">

</head>

<body>
  <div class="loader"></div>
  <div id="app">
    <section class="section">
      <div class="container mt-5">

{% block content %}
{% endblock %}

        </div>
      </div>
    </section>
  </div>



<!-- General JS Scripts -->
  <script src="{% static "assets/js/app.min.js" %}"></script>
  <!-- JS Libraies -->
  <!-- Page Specific JS File -->
  <!-- Template JS File -->
  <script src="{% static "assets/js/scripts.js" %}"></script>
  <!-- Custom JS File -->
  <script src="{% static "assets/js/custom.js" %}"></script>
  <script src="{% static "assets/bundles/izitoast/js/iziToast.min.js" %}"></script>

  {% block js%}
  {% endblock %}

  

</body>



</html>

accounts/templates/accounts/auth-login.html
{% extends 'accounts/auth-base.html' %}

{% block title %}Login | HRInventory {% endblock %}
{% load static %}


{% block content %}
        

        <div class="row">
          <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
            

            <div class="card card-primary"><br>
              <center><img src="{% static "assets/img/vistan-logo1.png" %}" width="65%" height="80%" class="" alt=""></center>
              <div class="card-header"></div>
              <div class="card-header">
                
                <h4>Login</h4>
              </div>
              <div class="card-body">
                <form method="POST" class="needs-validation" novalidate="">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input id="email" type="text" class="form-control" name="username" tabindex="1" required autofocus>
                    <div class="invalid-feedback">
                      Please fill in your username
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="d-block">
                      <label for="password" class="control-label">Password</label>
                     
                    </div>
                    <input id="password" type="password" class="form-control" name="password" tabindex="2" required>
                    <div class="invalid-feedback">
                      please fill in your password
                    </div>
                  </div>
                  
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                      Login
                    </button>
                  </form><br>
                
                </div>
               
              </div>
            </div>
            
        </div>

{% endblock %}

{% block js %}

{% if messages%}
  <script>
        iziToast.show({
                        title: '',
                        message: '{% for i in messages %}{{i}}{%endfor%}',
                        position: 'topRight',
                        color: 'red'
<<<<<<< HEAD
                        
                          {% for i in messages%}
                          {% if 'danger' ==  i.tags %} red
                          {% else %} green
                          {% endif%}
                        {% endfor %} 
=======

>>>>>>> 0c0eb237740f9611876d3388860f3346af24ca73
                    });
  </script>
  {% endif %}

{% endblock %}

accounts/templates/accounts/create_dept.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
        Add Department | Vistan Nextgen Pvt Ltd
{% endblock%}
            


{% block content %}
      
      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <ul class="breadcrumb breadcrumb-style ">
            
            <li class="breadcrumb-item">
              <a href="index-2.html">
                <i data-feather="home"></i></a>
            </li>
            <!-- <li class="breadcrumb-item active">Dashboard</li>    -->
            <li class="breadcrumb-item active">Add Department</li>                   
          </ul>      


            <div class="card">
                <div class="card-header">
                <h4>Add Category</h4>
            </div>
                  
            <div class="card-body">       
                <div class="container">
                    <form method = "POST">
                        {% csrf_token %}
                    <div class="col-md-12">                        
                        <div class="form-group">
                         <label>Name</label>
                         <input type="text" name = "dept_name" class="form-control">
                         </div>
                     </div>

                     <div class="col-12">
                         <div class="form-group pmd-textfield pmd-textfield-floating-label">
                             <label>Description</label>
                             <textarea name = "dept_description" class="form-control" id="reason" name="reason"></textarea>
                         </div>
                     </div>
                     <div class="footer">
                         <button class="btn btn-primary">Submit</button>
                     </div>
                    </form>
                </div> 
               </div>    
        </section>
      </div>
    </div>
{% endblock %}

accounts/templates/accounts/emp_table.html
<div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Employee List</h4>
                    <div class="card-header-form">
                      
                      <form>
                        
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search by name" id = "myInput" onkeyup="myFunction()">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                          
                          
                          <a href="{% url 'accounts:auth-register' %}"><div class="badge badge-secondary">Add Employee</div></a>
                          

                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="table-responsive">
                  <div class="card-body p-0">
                      <table class="table table-striped" id = "myTable">
                        <tr>
                          <th class="text-center" onclick="sortTable(0)">Employee ID&nbsp;<i class="fas fa-sort"></i></th>
                          <th onclick="sortTable(1)">Employee Name&nbsp;<i class="fas fa-sort"></i></th>
                          <th>Department</th>
                          <th>Designation</th>
                          <th>Mobile</th>                         
                          <th>Action</th>
                        </tr>
                        {% for i in emp %}
                        <tr>
                          

                              <td class="p-0 text-center">
                                  {{i.employee_id}}
                            
                              </td>
                              <td>{{i.username}} {{i.last_name}}</td>
                              <td>{{i.department}}</td>
                              <td>{{i.designation}}</td>

                              
                         
                          
                          <td>
                            {{i.mobile}}
                          </td>

                              <td>
                                {% comment %} <a class="btn btn-md btn-dark" style="text-decoration: none;" href=""
                                  data-toggle="tooltip" data-placement="top"
                                  title="view."
                                ><i class="fas fa-eye"></i> </a>&nbsp; {% endcomment %}


                                <a class="btn btn-md btn-info" style="text-decoration: none;" 
                                   href="{% url 'accounts:edit-employee' i.id %}"
                                  data-toggle="tooltip" data-placement="top"
                                  title="edit"
                                ><i class="fas fa-pen"></i> </a>&nbsp;

                                <a class="btn btn-md btn-warning" style="text-decoration: none;" 
                                   href="{% url 'accounts:change-password' i.id %}"
                                  data-toggle="tooltip" data-placement="top"
                                  title="Change Password"
                          
                                ><i class="fas fa-key"></i> </a>&nbsp; 

                                {% comment %} <a class="btn btn-md btn-danger" style="text-decoration: none;" 
                                   href="{% url 'accounts:delete-employee' i.id%}"
                                  data-toggle="tooltip" data-placement="top"
                                  title="Delete"
                                ><i class="fas fa-trash"></i> </a>&nbsp;                                                             {% endcomment %}
                              </td>                          
                        </tr> 

                        {% endfor %}   
                       
                     
                      </table>
                    </div>
                  </div>
                </div>
              </div>
</div>

{% block js %}

{% if messages%}
  <script>
        iziToast.show({
                        title: 'yay!!',
                        message: '{% for i in messages %}{{i}}{%endfor%}',
                        position: 'topRight',
                        color: 'green'
                         {% for i in messages%}
                          {% if 'danger' == i.tags %} red
                          {% else %} green
                          {% endif%}
                         {% endfor %} 
                    });
  </script>
  {% endif %}

{% endblock %}