InventoryProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from accounts.views import LoginView


urlpatterns = [
    path('dj-admin/', admin.site.urls),

    path('test', views.Test),

    path('', LoginView, name = 'login'),
    
    # including Apps urls
    path('accounts/', include('accounts.urls')),
    path('components/', include('components.urls')),
    path('bag/', include('bag.urls')),
    path('order/', include('order.urls')),
    path('leave/', include('leave.urls')),
    path('dashboard/', include('dashboard.urls')),

]

bag/urls.py
from django.urls import path
from . import views

app_name = 'bag'

urlpatterns = [
    path('add-to-bag/<str:component_id>', views.add_to_bag, name = 'add_to_bag'),
    path('bag-details/', views.bag_details, name = 'bag_details'),
    path('remove-item/<str:component_id>', views.remove_item, name = 'remove-item'),
    path('delete-item/<str:component_id>', views.delete_bag_items, name = 'delete-items'),
    path('request-components', views.request_components, name = 'request_components')
]

components/urls.py
from django.urls import path
from . import views

app_name = 'components'

urlpatterns = [
    path('',views.ComponentListView, name = 'component-list-all'),  
    path('<str:id>/', views.CatComponentListView, name =  'component-list-cat'),
    
    path('category/all', views.all_categories, name = 'all-categories'),
    path('add/category', views.add_category, name = 'add-category'),
    path('update/category/<str:id>', views.update_category, name = 'update-category'),
    path('delete/category/<str:id>', views.delete_category, name='delete-category'),
    path('detail/component/<str:id>', views.detailed_component, name = 'component-detail'),


    path('admin/all', views.allcomponents, name = 'all-components-admin'),
    path('admin/add-component', views.add_component, name = 'add-component'),
    path('admin/update-component/<str:id>', views.update_component, name = 'update-component'),
    path('admin/delete-component/<str:id>', views.delete_component, name = 'delete-component'),

]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('success/', views.order_success, name = 'order_success'),
    path('orders/', views.user_orders, name = 'user-orders'),
    path('order-detail/<str:id>', views.order_detail, name = 'order-detail'),
    path('order-detail-admin/<str:id>', views.order_detail_admin, name='order-detail-admin'),
    path('all-orders/', views.all_order, name = 'all-orders'),  
    path('order-accept/<str:id>/', views.order_accept, name = 'order-accept'),
    path('order-decline/<str:id>', views.order_decline, name = 'order-decline'),
    path('order-return/<str:id>', views.order_return, name = 'order-return'),
    path('order-deploy/<str:id>', views.order_deploy, name = 'order-deploy'),
    # path('deploy-details', views.deploy_details, name = 'deploy-details-post'),

    path('deploy-list/admin', views.deployed_list_admin, name = 'admin-deploy-list'),
    path('deploy-list/user/<str:id>', views.deployed_list_user, name = 'user-deploy-list'),

    path('deploy-detail/<str:id>', views.deployed_detail, name = 'deploy-detail')
]

order/models.py
from django.db import models


###################################################
################  ORDER MODEL   ###################
###################################################
 
class Order(models.Model):    
    def auto_order_id(): 
        no = Order.objects.count()
        str1 = 'VSTNORDER'
        list2 = ['0','0','0','0','0', '0']
        item = no+1   
        str_item = str(item)   
        list_item = list(str_item)   
        leng = len(list_item)
        con = 6-leng   
        list2[con:] = list_item
        result = ''.join(map(str, list2))
        final = str1+result   
        return final

    order_id = models.CharField(max_length = 25,default=auto_order_id, editable = False)
    created_at = models.DateTimeField(auto_now_add = True)
    username = models.CharField(max_length =25, editable=False)
    email = models.CharField(max_length =100, editable=False)
    order_choices = (
        ('requested', 'requested'),
        ('approve', 'approve'),
        ('decline', 'decline'),
        ('deploy', 'deploy'),
        ('return', 'return'),
        
    )
    status = models.CharField(max_length = 50, choices = order_choices, default='requested')

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'
        ordering = ('-created_at',)

    def __str__(self):
        return str(self.order_id)

###################################################
############  ORDER ITEM MODEL    #################
###################################################

class OrderItem(models.Model):
    component = models.CharField(max_length = 40)
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete = models.CASCADE)
    
    class Meta:
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Items'
        ordering = ('-id',)

    def __str__(self):
        return self.component


##################################################
###########    DEPLOYMENT MODEL   ################
##################################################

class Deployment(models.Model):
    def auto_dep_id(): 
        no = Deployment.objects.count()
        str1 = 'VSTDEP'
        list2 = ['0','0','0','0','0', '0']
        item = no+1   
        str_item = str(item)   
        list_item = list(str_item)   
        leng = len(list_item)
        con = 6-leng   
        list2[con:] = list_item
        result = ''.join(map(str, list2))
        final = str1+result   
        return final

    deployment_id = models.CharField(max_length = 20, editable = False, default = auto_dep_id)
    created_at = models.DateTimeField(auto_now_add=True)
    username = models.CharField(max_length = 30, editable = False)
    email = models.CharField(max_length = 30, editable = False)

    class Meta:
        verbose_name = 'Deployment'
        verbose_name_plural = 'Deployment'
        ordering = ('-id',)

    def __str__(self):
        return str(self.deployment_id)

class DeployedItems(models.Model):
    component = models.CharField(max_length = 100)
    quantity = models.IntegerField()
    deployment = models.ForeignKey(Deployment, on_delete = models.CASCADE)
    deployed_by = models.CharField(max_length = 40, blank=True, null = True)
    deployed_into = models.CharField(max_length=50, blank=True, null = True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'Deployed Item'
        verbose_name_plural = 'Deployed Items'
        ordering = ('-id',)

    def __str__(self):
        return self.component

order/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import user_passes_test
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from order.models import Order, OrderItem, Deployment, DeployedItems
from django.contrib.auth.decorators import user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from components.models import Component
from accounts.models import CustomUser as User

# Create your views here.

def is_employee(user):
    return user.groups.filter(name='employee').exists()


###############    ORDER FUNCTIONALITIES FOR EMPLOYEE    ########################
@user_passes_test(is_employee)
def order_success(request):
    return render(request, 'order/order_success.html')

@user_passes_test(is_employee)
def user_orders(request):
    orders = Order.objects.filter(username = request.user.username)
    # print(orders)

    return render(request, 'order/orders.html', {'orders':orders})

@user_passes_test(is_employee)
def order_detail(request, id):
    order = Order.objects.get(id = id)
    # print(order)
    oi = OrderItem.objects.filter(order_id = order)
    # print(oi)

    return render(request, 'order/order_detail.html', {'oi':oi, 'order':order})



################   ORDER FUNCTIONALITIES BY ADMIN    ########################
@staff_member_required(login_url='accounts:auth-login')
def all_order(request):
    orders = Order.objects.all()
    return render(request, 'order/all_orders.html',{'orders':orders})

@staff_member_required(login_url='accounts:auth-login')
def order_detail_admin(request, id):
    order = Order.objects.get(id = id)
    # print(order)
    oi = OrderItem.objects.filter(order_id = order)
    # print(oi)

    return render(request, 'order/order_detail_admin.html', {'oi':oi, 'order':order})


@staff_member_required(login_url='accounts:auth-login')
def order_accept(request, id):
    order = Order.objects.get(id = id)
    if order.status == 'requested':
        order.status = 'approve'
        order.save()
        messages.info(request, 'Component request has approved')   
    return redirect('order:all-orders')


@staff_member_required(login_url='accounts:auth-login')
def order_decline(request, id):
    order = Order.objects.get(id = id)
    if order.status == 'requested':
        # print('status = requested')
        order.status = 'decline'
        order.save()

        oi = OrderItem.objects.filter(order_id = order)
        # print(oi)

        for i in oi:
            oi_id = i.order_id
            oi_name = i.component
            oi_quantity = i.quantity

            # print(oi_quantity)
            
            component = Component.objects.get(name = oi_name)
            # print()
            # print(component.stock)
            # print()
            component.stock = component.stock + oi_quantity
            component.save()

        messages.info(request, 'Component request has declined')   
    return redirect('order:all-orders')

@staff_member_required(login_url='accounts:auth-login')
def order_return(request, id):
    order = Order.objects.get(id = id)
    oi = OrderItem.objects.filter(order_id = order)

    if order.status == 'approve':
        order.status = 'return'
        order.save()

        for i in oi:
            oi_name = i.component
            oi_quantity = i.quantity

            component = Component.objects.get(name = oi_name)
            
            component.stock = component.stock + oi_quantity
            component.save()

            messages.info(request, 'component returned successfully')

    return redirect('order:all-orders')



@staff_member_required(login_url='accounts:auth-login')
def order_deploy(request, id):
    order = Order.objects.get(id = id)
    oi = OrderItem.objects.filter(order_id = order)

    if request.method == "POST":
        
        # try:
        if order.status == 'approve':
            order.status = 'deploy'
            order.save()
            
            deployment = Deployment.objects.create(
                                                    username = order.username,
                                                    email = order.email    
                                                    )
            deployment.save()                


            for i in oi:
                oi_name = i.component
                oi_quantity = i.quantity

                deployment_item = DeployedItems.objects.create(
                                                                    component = oi_name,
                                                                    quantity = oi_quantity,
                                                                    deployment = deployment,
                                                                    deployed_by = order.username,
                                                                    deployed_into = request.POST['deployed_into'] 
                                                                )
                deployment_item.save()
                messages.info(request, 'items added to deployment list')
    
        # except ObjectDoesNotExist:
        #     pass
    return redirect('order:all-orders')

@staff_member_required(login_url='accounts:auth-login')
def deployed_list_admin(request):
    deployment = Deployment.objects.all().order_by('-id')
    return render(request, 'order/deploy_list_admin.html', {'deployment':deployment})

@user_passes_test(is_employee)
def deployed_list_user(request, id):
    user = User.objects.get(id = id)
    deployment = Deployment.objects.filter(username = user.username)    
    return render(request, 'order/deploy_list_user.html', {'deployment':deployment})

def deployed_detail(request, id):
    deployment = Deployment.objects.get(id =id)
    dep_items = DeployedItems.objects.filter(deployment = deployment)

    # print(dep_items)

    return render(request, 'order/deploy_detail.html', {'deployment':deployment, 'dep_items':dep_items})

order/templates/order/all_orders_table.html
<div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Orders List</h4>
                    <div class="card-header-form">
                      
                      <form>
                        
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search by name" id = "myInput" onkeyup="myFunction()">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                          
                          
                          
                          

                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="table-responsive">
                  <div class="card-body p-0">
                      <table class="table table-striped" id = "myTable">
                        <tr>
                          <th class="text-center" onclick="sortTable(0)">Order ID&nbsp;<i class="fas fa-sort"></i></th>
                          <th onclick="sortTable(1)">Username&nbsp;<i class="fas fa-sort"></i></th>
                          <th>Date of Order</th>
                          <th>Status</th>
                          <th>Action</th>
                          
                          
                         
                        </tr>
                        {% for i in orders %}
                        <tr>
                          

                              <td class="p-0 text-center">
                                  {{i.order_id}}
                                </div>
                              </td>
                              <td>{{i.username}}</td>
                              <td>{{i.created_at|date:"d-m-Y"}}</td>
                              
                              <td>
                                {% ifequal i.status 'requested'%} <div class="badge badge-secondary">{{i.status|title}}</div> {% endifequal %}
                                {% ifequal i.status 'approve'%} <div class="badge badge-success">{{i.status|title}}d</div> {% endifequal %}
                                {% ifequal i.status 'decline'%} <div class="badge badge-danger">{{i.status|title}}d</div> {% endifequal %}
                                {% ifequal i.status 'return'%} <div class="badge badge-warning">{{i.status|title}}ed</div> {% endifequal %}
                                {% ifequal i.status 'deploy' %} <div class="badge badge-dark">{{i.status|title}}ed</div>{% endifequal %}
                              </td>

                              
                                         
                         
                          
                         

                             

                              <td>
                                <a class="text-center" 
                                               href="{% url 'order:order-detail-admin' i.id %}">
                                               View Order
                                               </a>
                              </td>

                          
                              
                        </tr>  
                        {% endfor %}   
                       
                      </table>
                    </div>
                  </div>
                </div>
              </div>
</div>

{% block js %}

{% if messages%}
  <script>
        iziToast.show({
                        title: 'yay!!',
                        message: '{% for i in messages %}{{i}}{%endfor%}',
                        position: 'topRight',
                        color: 'green'
                        /* {% for i in messages%}
                          {% ifequal 'danger' i.tags %} red
                          {% else %} green
                          {% endifequal%}
                        {% endfor %} */
                    });
  </script>
  {% endif %}

{% endblock %}

order/templates/order/order_detail.html
{% extends 'base.html' %}

{% block title %}
    Orders - {{request.user.username}} | Vistan Nextgen
{% endblock %}

{% block content %}
<!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <ul class="breadcrumb breadcrumb-style ">
            
            <li class="breadcrumb-item">
              <a href="index-2.html">
                <i data-feather="home"></i></a>
            </li>
            
            <li class="breadcrumb-item active">Order Detail</li>                   
          </ul>

          <div class="container">

            <div class="card">
              <div class="card-header">
                    
                    
                       <h4>Order Details</h4> 
                       
                    
              </div>
              
              
              <div class="card-body">
                {% if order %}
                    Order ID &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     :  &nbsp;&nbsp; <span style="color: black;">{{order}}</span><br><br>
                    Order Status&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  : &nbsp;&nbsp;  
                    
                    {% ifequal 'requested' order.status %}<div class="badge badge-secondary">{{order.status|title}}</div>{% endifequal %}
                    {% ifequal 'approve' order.status %}<div class="badge badge-success">{{order.status|title}}d</div>{% endifequal %}
                    {% ifequal 'decline' order.status %}<div class="badge badge-danger">{{order.status|title}}d</div>{% endifequal %}
                    {% ifequal 'return' order.status %}<div class="badge badge-warning">{{order.status|title}}ed</div>{% endifequal %}
                    {% ifequal 'deploy' order.status %}<div class="badge badge-dark">{{order.status|title}}ed</div>{% endifequal %}



                    
                    <br><br>
                    Date of request&nbsp;&nbsp;  :&nbsp;&nbsp;  <span style="color: black;">{{order.created_at|date:"d-m-Y"}}</span>
                {% endif %} <br><br>                
              </div>

              <div class="row">
                <div class="col-1">

                </div>

                <div class="col-9 col-md-6 col-lg-6 col-sm-12">
                  <div class="card">
                    <div class="card-header">
                      <h4>Component Details</h4>
                      
                      {% comment %} {% if order %}  
                        {% ifequal 'approve' order.status %}
                        <div class="card-header-form">                         
                            <div class="input-group">                            
                                <a href="{% url 'order:order-return' order.id %}" class="btn btn-danger" href="">Return</a>                            
                            </div>                        
                        </div>
                        {% endifequal %}
                      {% endif %} {% endcomment %}
                      
                    </div>
                    <div class="card-body p-0">
                      <div class="table-responsive">
                        <table class="table table-striped table-md">
                          <tr>                           
                            <th class="text-center">Component Name</th>
                            <th class="text-center">Quantity</th>                          
                          </tr>

                          
                          {% for i in oi %}
                
                          <tr>
                            
                            <td class="text-center">{{i.component}}</td>
                            <td class="text-center">{{i.quantity}}</td>
                            
                          </tr>
                            
                          {% endfor %}                          
                          
                        </table>
                      </div>
                    </div>
              </div>
                
            </div>

                <div class="col-2">

                </div>
              </div>        

        </section>
    </div>  
{% endblock %}

order/templates/order/order_detail_admin.html
{% extends 'base.html' %}

{% block title %}
    Order Detail| Vistan Nextgen
{% endblock %}

{% block content %}
<!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <ul class="breadcrumb breadcrumb-style ">
            
            <li class="breadcrumb-item">
              <a href="index-2.html">
                <i data-feather="home"></i></a>
            </li>
            
            <li class="breadcrumb-item active">Order Detail</li>                   
          </ul>

          <div class="container">

            <div class="card">
              <div class="card-header">
                    
                    
                       <h4>Order Details</h4> 
                       
                    
              </div>
              
              
              <div class="card-body">
                {% if order %}
                    Order ID &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     :  &nbsp;&nbsp; <span style="color: black;">{{order}}</span><br><br>
                    Order by &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     :  &nbsp;&nbsp; <span style="color: black;">{{order.username}}</span><br><br>
                    
                    Order Status&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  : &nbsp;&nbsp;  
                    
                    
                    {% ifequal order.status 'requested' %} <div class="badge badge-secondary">{{order.status|title}}</div>{% endifequal %}
                    {% ifequal order.status 'approve' %} <div class="badge badge-success">{{order.status|title}}d</div>{% endifequal %}
                    {% ifequal order.status 'decline' %} <div class="badge badge-danger">{{order.status|title}}d</div>{% endifequal %}
                    {% ifequal order.status 'return' %} <div class="badge badge-warning">{{order.status|title}}ed</div>{% endifequal %}
                    {% ifequal order.status 'deploy' %} <div class="badge badge-dark">{{order.status|title}}ed</div>{% endifequal %}
                    
                    
                    
                    <br><br>
                    Date of request&nbsp;&nbsp;  :&nbsp;&nbsp;  <span style="color: black;">{{order.created_at|date:"d-m-Y"}}</span>
                {% endif %} <br><br>                
              </div>

              <div class="row">
                <div class="col-1">

                </div>

                <div class="col-9 col-md-6 col-lg-6">
                  <div class="card">
                    <div class="card-header">
                      <h4>Component Details</h4>
                      {% if order %}  
                        {% ifequal 'requested' order.status %}
                        <div class="card-header-form">                         
                            <div class="input-group">                            
                                <a href = "{% url 'order:order-accept' order.id %}" class="btn btn-success" href="">approve</a>  
                                <a href="{% url 'order:order-decline' order.id %}" class="btn btn-warning">decline</a>                          
                            </div>                                                   
                        </div>
                        {% endifequal %}

                       
                        {% ifequal 'approve' order.status %}
                        <div class="card-header-form">                         
                            <div class="input-group"> 
                                 <a 
                                    data-toggle="modal" data-target="#exampleModal"
                                    href="{% url 'order:order-deploy' order.id %}"
                                    class = "btn btn-dark"
                                    
                                    >
                                    

                                    Deploy
                                  </a>                          
                                <a href="{% url 'order:order-return' order.id %}" class="btn btn-danger" href="">Return</a>                            
                            </div>                        
                        </div>
                        {% endifequal %}
                      


                      {% endif %}
                      
                    </div>
                    <div class="card-body p-0">
                      <div class="table-responsive">
                        <table class="table table-striped table-md">
                          <tr>                           
                            <th class="text-center">Component Name</th>
                            <th class="text-center">Quantity</th>                          
                          </tr>

                          
                          {% for i in oi %}
                
                          <tr>
                            
                            <td class="text-center">{{i.component}}</td>
                            <td class="text-center">{{i.quantity}}</td>
                            
                          </tr>
                            
                          {% endfor %}                          
                          
                        </table>
                      </div>
                    </div>
              </div>
                
            </div>

                <div class="col-2">

                </div>
              </div>        

        </section>
    </div>  

    
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="formModal"
          aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">

              <div class="modal-body">
                <form method="POST" action = "{% url 'order:order-deploy' order.id%}">
                  {% csrf_token %}
                  <div class="form-group">
                    <label>Deployed into: </label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <div class="input-group-text">
                          <i class="fas fa-project-diagram"></i>
                        </div>
                      </div>
                      <input type="text" class="form-control" placeholder="project_name" name="deployed_into">
                    </div>
                  </div>
                  {% comment %} <a class = "btn btn-dark" href="">Submit</a> {% endcomment %}

                </form>
              </div>
            </div>
          </div>
    </div>




{% endblock %}

order/templates/order/orders.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Orders - {{request.user.username}} | Vistan Nextgen
{% endblock %}

{% block content %}
<!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <ul class="breadcrumb breadcrumb-style ">
            
            <li class="breadcrumb-item">
              <a href="index-2.html">
                <i data-feather="home"></i></a>
            </li>
            <li class="breadcrumb-item active">Your Orders</li>                   
          </ul>
            

          {% if orders %}

          <div class="container">
            <div class="card">
              <div class="card-header">Your Orders</div>

              <div class="row">
                <div class="col-1">

                </div>
                <div class="col-9 card-body">
                  {% for i in orders%}
                    {{i.order_id}} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    {% ifequal i.status 'requested' %}<div class="badge badge-secondary">{{i.status}}</div> {% endifequal %}
                    {% ifequal i.status 'approve' %}<div class="badge badge-success">{{i.status}}d</div> {% endifequal %}
                    {% ifequal i.status 'decline' %}<div class="badge badge-danger">{{i.status}}d</div> {% endifequal %}
                    {% ifequal i.status 'return' %}<div class="badge badge-warning">{{i.status}}ed</div> {% endifequal %}
                    {% ifequal i.status 'deploy' %}<div class="badge badge-dark">{{i.status}}ed</div> {% endifequal %}
                    
                    
                    
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{i.created_at|date:"d-m-Y"}}
                    &nbsp;&nbsp;&nbsp;&nbsp;<a class="text-center" href="{% url 'order:order-detail' i.id %}">View Order</a> <br><br>
                  {% endfor %}
                </div>
                <div class="col-2"></div>
              </div>
             </div>
              
          </div>
          {% else %}

          <div class="col-md-12 col-sm-12 col-12">
            <div class="card">
              <div class="card-header">
                <h4>Your Orders</h4>
              </div>
              <div class="card-body"><br>
                  <div class="row">

                    <div class="col-sm-7 col-md-6 text-center">
                        <img src="{% static "assets/img/ec1.png" %}" 
                        width: 100%;
                        height: auto;><br>
                        <h5 class="text-center">No more<span style="color: orangered;"> orders!</span></h5>                  
                       
                    </div>
                    <div class="col-sm-5 col-md-6"><br><br><br><br>
                        <center><h5 class="text-center"> Want to <span style="color: orange;"> make Orders ?</span></h5><br>
                        <a  href="{% url 'components:component-list-all' %}" class="btn btn-md btn-outline-dark">Click here</a></center>
                    </div>                   
                  </div>               
               <br><br><br>
              </div>
            </div>
          </div>
        </div>

          No Orders!!!

          {% endif %}

        </section>
    </div>  
{% endblock %}