InventoryProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from accounts.views import LoginView


urlpatterns = [
    path('dj-admin/', admin.site.urls),

    path('test', views.Test),

    path('', LoginView, name = 'login'),
    
    # including Apps urls
    path('accounts/', include('accounts.urls')),
    path('components/', include('components.urls')),
    path('bag/', include('bag.urls')),
    path('order/', include('order.urls')),
    path('leave/', include('leave.urls')),
    path('dashboard/', include('dashboard.urls')),

]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('auth-login/', views.LoginView, name = 'auth-login'),
    path('auth-register/', views.RegisterEmployee, name = 'auth-register'),
    path('auth-logout/', views.LogoutView, name = 'auth-logout'),
    path('auth-change-password/', views.ChangePasswordView, name = 'auth-change-password'),

    path('all-employees', views.allEmployees, name = 'all-employes'),
    path('edit-employee/<str:id>', views.editEmployee, name = 'edit-employee'),
    path('edit-profile/<str:id>', views.editUserProfile, name = 'edit-user-profile'),
    path('delete-employee/<str:id>', views.deleteEmployee, name = 'delete-employee'),
    path('change-password/<str:id>', views.ChangePasswordView, name = 'change-password'),

    path('add-department/', views.create_dept, name = 'create-dept'),
    path('update-dept/<str:id>', views.update_dept, name = 'update-dept'),
    path('delete-dept/<str:id>', views.delete_dept, name = 'delete-dept'),
    path('all-depts', views.dept_list, name = 'all-depts'),

]

bag/urls.py
from django.urls import path
from . import views

app_name = 'bag'

urlpatterns = [
    path('add-to-bag/<str:component_id>', views.add_to_bag, name = 'add_to_bag'),
    path('bag-details/', views.bag_details, name = 'bag_details'),
    path('remove-item/<str:component_id>', views.remove_item, name = 'remove-item'),
    path('delete-item/<str:component_id>', views.delete_bag_items, name = 'delete-items'),
    path('request-components', views.request_components, name = 'request_components')
]

components/urls.py
from django.urls import path
from . import views

app_name = 'components'

urlpatterns = [
    path('',views.ComponentListView, name = 'component-list-all'),  
    path('<str:id>/', views.CatComponentListView, name =  'component-list-cat'),
    
    path('category/all', views.all_categories, name = 'all-categories'),
    path('add/category', views.add_category, name = 'add-category'),
    path('update/category/<str:id>', views.update_category, name = 'update-category'),
    path('delete/category/<str:id>', views.delete_category, name='delete-category'),
    path('detail/component/<str:id>', views.detailed_component, name = 'component-detail'),


    path('admin/all', views.allcomponents, name = 'all-components-admin'),
    path('admin/add-component', views.add_component, name = 'add-component'),
    path('admin/update-component/<str:id>', views.update_component, name = 'update-component'),
    path('admin/delete-component/<str:id>', views.delete_component, name = 'delete-component'),

]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('user/<str:id>', views.user_dashboard, name = 'user-dashboard'),
    path('admin/', views.admin_dashboard,  name = 'admin-dashboard'),
    
]

leave/urls.py
from django.urls import path
from . import views

app_name = 'leave'


urlpatterns = [
    path('apply-leave', views.apply_leave, name = 'apply-leave'),
    path('all-leaves-list', views.leave_list_admin, name = 'all-leaves'),
    path('user-leaves-list/<str:username>', views.leaves_list_user, name = 'user-leaves'),
    path('leave-detail-admin/<str:id>', views.leave_detail_admin, name = 'leave-detail-admin'),
    path('approve-leave/<str:id>', views.approve_leave, name  = 'approve-leave'),
    path('decline-leave/<str:id>', views.decline_leave, name = 'decline-leave'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('success/', views.order_success, name = 'order_success'),
    path('orders/', views.user_orders, name = 'user-orders'),
    path('order-detail/<str:id>', views.order_detail, name = 'order-detail'),
    path('order-detail-admin/<str:id>', views.order_detail_admin, name='order-detail-admin'),
    path('all-orders/', views.all_order, name = 'all-orders'),  
    path('order-accept/<str:id>/', views.order_accept, name = 'order-accept'),
    path('order-decline/<str:id>', views.order_decline, name = 'order-decline'),
    path('order-return/<str:id>', views.order_return, name = 'order-return'),
    path('order-deploy/<str:id>', views.order_deploy, name = 'order-deploy'),
    # path('deploy-details', views.deploy_details, name = 'deploy-details-post'),

    path('deploy-list/admin', views.deployed_list_admin, name = 'admin-deploy-list'),
    path('deploy-list/user/<str:id>', views.deployed_list_user, name = 'user-deploy-list'),

    path('deploy-detail/<str:id>', views.deployed_detail, name = 'deploy-detail')
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render
from components.models import Component
from accounts.models import CustomUser as User
from order.models import Order, Deployment
from leave.models import Leave
from django.contrib.admin.views.decorators import staff_member_required


# Create your views here.

def is_employee(user):
    return user.groups.filter(name='employee').exists()


############     USER DASHBOARD     #################
@user_passes_test(is_employee)
def user_dashboard(request, id):
    user = User.objects.get(id = id)
    orders = Order.objects.filter(username = user.username).order_by('-id')[:5]
    deployments = Deployment.objects.filter(username = user.username).order_by('-id')
    leaves = Leave.objects.filter(user = user.username).order_by('-id')[:5]

    ord_len = len(orders)
    dep_len = len(deployments)

    return render(request, 'dashboard/user_dashboard.html', {'orders':orders, 
                                                             'deployments':deployments,
                                                             'leaves': leaves, 
                                                             'ord_len':ord_len, 
                                                             'dep_len':dep_len,
                                                             })



##############   ADMIN DASHBOARD   ##################
@staff_member_required(login_url='accounts:auth-login')
def admin_dashboard(request):
    components = Component.objects.all().order_by('-id')[:5]
    users = User.objects.all().order_by('-id')[:5]
    orders = Order.objects.all().order_by('-id')[:5]
    deployments = Deployment.objects.all().order_by('-id')[:5]
    leaves = Leave.objects.all().order_by('-id')[:5]

    comp_len = Component.objects.count()
    user_len = User.objects.count()
    ord_len = Order.objects.count()
    dep_len = Deployment.objects.count()

    return render(request, 'dashboard/admin_dashboard.html', {'components':components, 
                                                              'users' : users,
                                                              'orders' : orders,
                                                              'deployments': deployments,
                                                              'leaves' : leaves,
                                                              'comp_len' : comp_len,
                                                              'user_len' : user_len,
                                                              'ord_len' : ord_len,
                                                              'dep_len' : dep_len,
                                                               })

    
    

templates/admin-sidenav.html
<ul class="sidebar-menu">
            <li class="menu-header">ADMIN</li>
            
            <li>
              <a href="{%url 'dashboard:admin-dashboard' %}" ><i
                  data-feather="airplay"></i><span>Dashboard</span></a>
            </li>

            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="tag"></i><span>Component Orders</span></a>
              <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'order:all-orders' %}">Component Requests</a></li>
                {% comment %} <li><a class="nav-link" href="#">Component Dashboard</a></li> {% endcomment %}
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="calendar"></i><span>Leaves</span></a>
              <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'leave:all-leaves' %}">Leave Requests</a></li>
                {% comment %} <li><a class="nav-link" href="#">Leave Dashboard</a></li> {% endcomment %}
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="grid"></i><span>Components</span></a>
              <ul class="dropdown-menu">

                <li><a class="nav-link" href="{% url 'components:all-components-admin' %}">All Components</a></li>
                <li><a class="nav-link" href="{% url 'components:add-component' %}">add Components</a></li>                
                <li><a href="{% url 'components:all-categories' %}" class="nav-link">All Categories</a></li>
                <li><a class="nav-link" href="{% url 'components:add-category' %}">Add Category</a></li>
                {% comment %} <li><a class="nav-link" href="">Deployed Components</a></li> {% endcomment %}
                
                

              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="users"></i><span>Employees</span></a>
              <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'accounts:all-employes' %}">All Employees</a></li>

                <li><a class="nav-link" href="{% url 'accounts:auth-register' %}">Add Employees</a></li>

                <li><a class="nav-link" href="{% url 'accounts:all-depts' %}">All Departments</a></li>
                <li><a class="nav-link" href="{% url 'accounts:create-dept' %}">Add Departments</a></li>
                



              </ul>
            </li>

             <li>
              <a href="{% url 'order:admin-deploy-list' %}" ><i
                  data-feather="truck"></i><span>Deployment</span></a>
            </li>


            
            
            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="settings"></i><span>Settings</span></a>
              <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'accounts:edit-user-profile' user.id %}">Edit Profile</a></li>
                <li><a class="nav-link" href="{% url 'accounts:change-password' user.id %}">Change Password</a></li>
                <li><a class="nav-link" href="{% url 'accounts:auth-logout' %}">Logout</a></li>
                
</ul>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}


<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>{% block title %}{% endblock %}</title>
  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static "assets/css/app.min.css" %}">
  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
  <link rel="stylesheet" href="{% static "assets/css/components.css" %}">
  <link rel="stylesheet" href="{% static "assets/bundles/jqvmap/dist/jqvmap.min.css" %}">
  <!-- Custom style CSS -->
  <link rel="stylesheet" href="{% static "assets/css/custom.css" %}">
  <link rel="stylesheet" href="{% static "assets/css/mystyle.css" %}">

  <link rel='shortcut icon' type='image/x-icon' href="{% static "assets/img/favicon_vistan.ico" %}" />
  <link rel="stylesheet" href="{% static "assets/bundles/izitoast/css/iziToast.min.css" %}">
</head>

<body>
  <div class="loader"></div>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">      
      
        <!-- Side Navbar -->
        {% include 'navbar.html' %}
        {% include 'sidenav.html' %}

        {% block content %}
        {% endblock %}
      
      {% include 'footer.html' %}
    </div>
  </div>
  {% block js %}
  {% endblock %}
  <!-- General JS Scripts -->
  <script src="{% static "assets/js/app.min.js" %}"></script>
  <!-- JS Libraies -->
  <script src="{% static "assets/bundles/apexcharts/apexcharts.min.js" %}"></script>
  <script src="{% static "assets/bundles/amcharts4/core.js" %}"></script>
  <script src="{% static "assets/bundles/amcharts4/charts.js" %}"></script>
  <script src="{% static "assets/bundles/amcharts4/animated.js" %}"></script>
  <script src="{% static "assets/bundles/jqvmap/dist/jquery.vmap.min.js" %}"></script>
  <script src="{% static "assets/bundles/jqvmap/dist/maps/jquery.vmap.world.js" %}"></script>
  <!-- Page Specific JS File -->
  <script src="{% static "assets/js/page/index.js" %}"></script>
  <!-- Template JS File -->
  <script src="{% static "assets/js/scripts.js" %}"></script>
  <!-- Custom JS File -->
  <script src="{% static "assets/js/custom.js" %}"></script>
  <script src="{% static "assets/bundles/izitoast/js/iziToast.min.js" %}"></script>

</body>

</html>

templates/footer.html
      <footer class="main-footer">
        <div class="footer-left">
          Copyright &copy; 2021 <div class="bullet"></div> <a href="#">Vistan Nextgen Pvt Ltd. </a>
        </div>
        <div class="footer-right">
        </div>
      </footer>

templates/main-cards.html
<div class="row ">
            <div class="col-xl-3 col-lg-6">
               <div class="card l-bg-cherry">
                <div class="card-statistic-3 p-4">
                  <div class="card-icon card-icon-large"><i class="fas fa-users"></i></div>
                  <div class="mb-4">
                    <h4 class="card-title mb-0">Employees &nbsp;&nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp;25</h4>
                  </div>
                 
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6">
              <div class="card l-bg-blue-dark">
                <div class="card-statistic-3 p-4">
                  <div class="card-icon card-icon-large"><i class="fas fa-users"></i></div>
                  <div class="mb-4">
                    <h4 class="card-title mb-0">Components &nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp; 25 </h4>
                  </div>
                 
                </div>
              </div>
            </div>
        
             <div class="col-xl-3 col-lg-6">
              <div class="card l-bg-green-dark">
                <div class="card-statistic-3 p-4">
                  <div class="card-icon card-icon-large"><i class="fas fa-users"></i></div>
                  <div class="mb-4">
                    <h4 class="card-title mb-0">Transactions &nbsp;&nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp;25 </h4>
                  </div>
                  
                  
                </div>
              </div>
            </div>

            <div class="col-xl-3 col-lg-6">
              <div class="card l-bg-orange-dark">
                <div class="card-statistic-3 p-4">
                  <div class="card-icon card-icon-large"><i class="fas fa-users"></i></div>
                  <div class="mb-4">
                    <h4 class="card-title mb-0">testcard&nbsp;&nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp;<b>25</b> </h4>
                  </div>
                 
                </div>
              </div>
            </div>
          </div>

templates/navbar.html
{% load static %}
<div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar sticky">
        <div class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg
									collapse-btn"> <i data-feather="menu"></i></a></li>           
            
                {% if cat %}
                  <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown"
                    class="nav-link nav-link-lg message-toggle" style="color: black;">Select Category &nbsp;&#129175;
                    <span class="">
                    </span> </a>  
                                  
                  <div class="dropdown-menu DropdownMenuLink">  
                    <a href="{% url 'components:component-list-all' %}" style="text-decoration: none;">
                      <div class="dropdown-item">
                        all components
                      </div>
                    </a>                   

                    {% for i in cat%}  

                    <a href="{{i.get_url}}" style="text-decoration: none;">
                    <div class="dropdown-item">
                      {{i.name|lower}}
                    </div>
                  </a>
                    {% endfor %}
                  </div>

                  
                  
                </li>
                {% endif %}

                

          </ul>
        </div>
       <ul class="navbar-nav navbar-right">
          
            
        
    
            


         

          <li class="dropdown"><a href="#" data-toggle="dropdown"
              class="nav-link dropdown-toggle nav-link-lg nav-link-user"><i data-feather="user"></i><span class="d-sm-none d-lg-inline-block"></span></a>
            <div class="dropdown-menu dropdown-menu-right pullDown">
              <div class="dropdown-title">Hello {{user.username}}</div>
              <a href="{% url 'accounts:edit-user-profile' user.id %}" class="dropdown-item has-icon"> <i class="fas
										fa-user"></i> Profile
              </a> 
              <a href="{% url 'accounts:change-password' user.id %}" class="dropdown-item has-icon"> <i class="fas
										fa-key"></i>Reset Password
              </a> 
              <div class="dropdown-divider"></div>
              <a href="{% url 'accounts:auth-logout' %}" class="dropdown-item has-icon text-danger"> <i class="fas fa-sign-out-alt"></i>
                Logout
              </a>
            </div>
          </li>    
        

          
        </ul>
      </nav>

templates/sidenav.html
{% load static %}

<div class="main-sidebar sidebar-style-2 sticky">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href="{% url 'components:component-list-all' %}"> <img alt="image" src="{% static "assets/img/vistanlogo.png" %}" class="header-logo" /> 
            <span style="font-size: 65%;" class="logo-name">HR Inventory</span>
            </a>
          </div>
          
          <br><br>

          {% if request.user.is_staff %}
            {% include 'admin-sidenav.html' %} 

          {% else %}
          <ul class="sidebar-menu">
            <li class="menu-header">Employee</li>
            
            <li>
              <a href="{% url 'dashboard:user-dashboard' user.id %}" ><i
                  data-feather="airplay"></i><span>Dashboard</span></a>
            </li>
            <li class="dropdown">
            
              <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="grid"></i><span>Components</span></a>
              <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'components:component-list-all' %}">Request for components</a></li>
                {% comment %} <li><a class="nav-link" href="#">Component Notifications</a></li> {% endcomment %}
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown"><i
                  data-feather="calendar"></i><span>Leaves</span></a>
              <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'leave:apply-leave' %}">Request For Leave</a></li>
                <li><a class="nav-link" href="{% url 'leave:user-leaves' user.username%}">Leaves Dashboard</a></li>
              </ul>
            </li>
            <li >
              <a href="{% url 'bag:bag_details' %}" ><i data-feather="shopping-bag"></i><span>Your Bag</span></a>              
            </li>
            
            <li >
              <a href="{% url 'order:user-orders' %}" ><i data-feather="tag"></i><span>Your Orders</span></a>              
            </li>
            <li >
              <a href="{% url 'order:user-deploy-list' user.id %}" ><i data-feather="truck"></i><span>Your Deployments</span></a>              
            </li>
            
            
            <li class="dropdown">
              <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="settings"></i><span>Settings</span></a>
              <ul class="dropdown-menu">
                <li><a class="nav-link" href="{% url 'accounts:edit-user-profile' user.id %}">Edit Profile</a></li>
                <li><a class="nav-link" href="{% url 'accounts:change-password' user.id %}">Change Password</a></li>
                <li><a class="nav-link" href="#">Logout</a></li>
                
              </ul>
            </li>


            
           
          </ul>
          {% endif %}

          {% comment %} <li>
            {% for group_for in request.user.groups.all %}
                
                {% if group_for.name == 'employee' %}
                    USER IN EMPLOYEE GROUP
                {% elif group_for.name == 'hr' %}
                    Text showed to users in group 'hr'
                {% endif %} 
          {% endfor %}
          </li> {% endcomment %}


          </aside>
      </div>

templates/table.html
<div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Components</h4>
                    <div class="card-header-form">
                      <form>
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search" id = "myInput" onkeyup="myFunction()">
                          <div class="input-group-btn">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                  <div class="table-responsive">
                  <div class="card-body p-0">
                      <table class="table table-striped" id = "myTable">
                        <tr>
                          <th class="text-center">
                            <div class="custom-checkbox custom-checkbox-table custom-control">
                              <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad"
                                class="custom-control-input" id="checkbox-all">
                              <label for="checkbox-all" class="custom-control-label">&nbsp;</label>
                            </div>
                          </th>
                          <th>Component Name</th>
                          <th>Progress</th>
                          <th>Members</th>
                          <th>Due Date</th>
                          <th>Status</th>
                          <th>Action</th>
                        </tr>
                        <tr>
                          <td class="p-0 text-center">
                            <div class="custom-checkbox custom-control">
                              <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input"
                                id="checkbox-1">
                              <label for="checkbox-1" class="custom-control-label">&nbsp;</label>
                            </div>
                          </td>
                          <td>Create a mobile app</td>
                          <td class="align-middle">
                            <div class="progress" data-height="4" data-toggle="tooltip" title="100%">
                              <div class="progress-bar bg-success" data-width="100"></div>
                            </div>
                          </td>
                          <td>
                            <img alt="image" src="assets/img/users/user-5.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Wildan Ahdian">
                          </td>
                          <td>2018-01-20</td>
                          <td>
                            <div class="badge badge-success">Completed</div>
                          </td>
                          <td><a href="#" class="btn btn-primary">Detail</a></td>
                        </tr>
                        <tr>
                          <td class="p-0 text-center">
                            <div class="custom-checkbox custom-control">
                              <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input"
                                id="checkbox-2">
                              <label for="checkbox-2" class="custom-control-label">&nbsp;</label>
                            </div>
                          </td>
                          <td>Redesign homepage using react and BS4</td>
                          <td class="align-middle">
                            <div class="progress" data-height="4" data-toggle="tooltip" title="40%">
                              <div class="progress-bar" data-width="40"></div>
                            </div>
                          </td>
                          <td>
                            <img alt="image" src="assets/img/users/user-1.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Nur Alpiana">
                            <img alt="image" src="assets/img/users/user-3.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Hariono Yusup">
                            <img alt="image" src="assets/img/users/user-4.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Bagus Dwi Cahya">
                          </td>
                          <td>2018-04-10</td>
                          <td>
                            <div class="badge badge-info">Todo</div>
                          </td>
                          <td><a href="#" class="btn btn-primary">Detail</a></td>
                        </tr>
                        <tr>
                          <td class="p-0 text-center">
                            <div class="custom-checkbox custom-control">
                              <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input"
                                id="checkbox-3">
                              <label for="checkbox-3" class="custom-control-label">&nbsp;</label>
                            </div>
                          </td>
                          <td>Backup database</td>
                          <td class="align-middle">
                            <div class="progress" data-height="4" data-toggle="tooltip" title="70%">
                              <div class="progress-bar bg-warning" data-width="70"></div>
                            </div>
                          </td>
                          <td>
                            <img alt="image" src="assets/img/users/user-1.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Rizal Fakhri">
                            <img alt="image" src="assets/img/users/user-2.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Hasan Basri">
                          </td>
                          <td>2018-01-29</td>
                          <td>
                            <div class="badge badge-warning">In Progress</div>
                          </td>
                          <td><a href="#" class="btn btn-primary">Detail</a></td>
                        </tr>
                        <tr>
                          <td class="p-0 text-center">
                            <div class="custom-checkbox custom-control">
                              <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input"
                                id="checkbox-4">
                              <label for="checkbox-4" class="custom-control-label">&nbsp;</label>
                            </div>
                          </td>
                          <td>Input data</td>
                          <td class="align-middle">
                            <div class="progress" data-height="4" data-toggle="tooltip" title="100%">
                              <div class="progress-bar bg-success" data-width="100"></div>
                            </div>
                          </td>
                          <td>
                            <img alt="image" src="assets/img/users/user-2.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Rizal Fakhri">
                            <img alt="image" src="assets/img/users/user-5.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Isnap Kiswandi">
                            <img alt="image" src="assets/img/users/user-4.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Yudi Nawawi">
                            <img alt="image" src="assets/img/users/user-1.png" class="rounded-circle" width="35"
                              data-toggle="tooltip" title="Khaerul Anwar">
                          </td>
                          <td>2018-01-16</td>
                          <td>
                            <div class="badge badge-success">Completed</div>
                          </td>
                          <td><a href="#" class="btn btn-primary">Detail</a></td>
                        </tr>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
</div>